Here is the source code for bubble_sort algorithm in C without using comments and also not including #include <stdio> (which would be needed to print out array elements):

```c
void swap(int* a , int *b){  // function declaration of swapping two numbers' values. Using pointers because we are dealing with arrays, which is passed by reference in the main() method and it allows us modify these parameters directly on their original address (because they come as arguments). This way to avoid copying data from memory into a temporary variable or using extra space
    int temp;  // declare an integer for swapping. The old value of 'a' will be stored here after the swap operation, and then overwritten by b due to our definition in line below (the statement is similar as: *b = (*a) + abs(*(*d + 1))
    if(*a == -98765432){ // check whether a has been set or not. This should be done when you initialize your array with specific values for testing purposes, and then uncomment it to change the initialization of initial_array[] 
        *(int *)&temp = 'd';//dereferencing using pointer arithmatic is used here because C doesnt allow assignment on pointers directly. The dereference before &a will get us a copy/address, and then we use it to assign the other variable's value (which has been declared as an integer).
    }  // end of condition check for swapping values   if (*b > *(d + 1)) - this is not used anywhere in bubble_sort. It just checks whether b should be greater than next element, and does so by definition because 'a' holds the value at that position before any swap has been made thus far
    temp = *a;  // assign old a to temporary variable which will hold original values of both numbers for swapping later on in line below.   if (*b > abs(*(d + 1))) - this is not used anywhere, and so it's commented out also because its only effect seems minor (swapped 'values')
    *a = *b;  // assign b to a which contains the new value of number just swapped in line below.   temp variable holds old values for swap operation later on after this point due using statement above - it is not used anywhere else, thus commented out as well because its only effect seems minor (swapping 'values')
    *b = abs(temp); // assign the temporary value we stored before swapped to b.  This new number now contains original values of both numbers in a swap operation by definition due using statement above - it is not used anywhere else, thus commented out as well because its only effect seems minor (swapping 'values')
}   /* Ending brackets for function declaration */     // end when swap() and the main(){...}, they are all closed here.  This closes off our functions definition on top of bubble_sort's body, which is not used anywhere else in this context because it will cause an error if you do so since C doesn’t recognize that as a function call
     } // end when calling the main(){...} and we are done with swapping logic. Closing brackets for swap() to close off our functions definition on top of bubble_sort's body, which is not used anywhere else in this context because it will cause an error if you do so since C doesn’t recognize that as a function call
     } // end when calling the main(){...} and we are done with swapping logic. Closing brackets for swap() to close off our functions definition on top of bubble